name: release

on:
  release:
    types: [created]
jobs:
  generate:
    name: Create release-artifacts
    runs-on: macOS-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2.0.0
      - uses: mihails-strasuns/setup-dlang@v0.4.1
        with:
          compiler: ldc-1.18.0
      - name: Build
        run: dub build
      - name: Upload the artifacts
        uses: skx/github-action-publish-binaries@release-1.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: 'rfweblab_client'
